#!/bin/sh

echo "ok lets do this"

GEN=$1
K=$2
T=$3
L=$4

RDIR=/uufs/chpc.utah.edu/common/home/u0401321/mattOnly/RUFUS
#JELLYFISH="$RDIR/bin/externals/jellyfish-2.2.5/bin/jellyfish"
JELLYFISH="$RDIR/src/externals/jellyfish-2.2.5/bin/jellyfish"
SORT="$RDIR/scripts/sort"

#ulimit -v 3000000
ulimit -v 30000000
ulimit -a
if [ -e "$GEN.Jhash" ]
then
        echo "Skipping jelly, $GEN.Jhash alreads exists"
else

        echo "here"
        mkfifo $GEN.Jhash.temp
        mkfifo $GEN.fq
        bash $GEN | $RDIR/cloud/PassThroughSamCheck $GEN.Jelly.chr > $GEN.fq &
        /usr/bin/time -v $JELLYFISH count --disk -m $K -L $L -s 8G -t $T -o $GEN.Jhash -C $GEN.fq
        /usr/bin/time -v $JELLYFISH histo -f -o $GEN.Jhash.histo $GEN.Jhash 
        rm $GEN.Jhash.temp
        rm $GEN.fq

	wait
fi
wait
exit
