#!/bin/sh

echo "ok lets do this"

GEN=$1
OUT=$2
K=$3
T=$4

RDIR="/uufs/chpc.utah.edu/common/home/u0991464/d1/home/farrelac/bin/RUFUS_git/RUFUS"
JELLYFISH="$RDIR/src/externals/jellyfish-2.2.5/bin/jellyfish"
SORT="$RDIR/scripts/sort"
	
echo "$JELLYFISH"
$JELLYFISH


ulimit -v 120000000
ulimit -a
if [ -e "$OUT.sorted.min2.tab" ]
then
        echo "Skipping jelly, $ParentGenerator.Jhash.sorted.min2.tab alreads exists"
else
	echo "here"
	mkfifo $OUT.temp
	$JELLYFISH count -G 20 -g $GEN -m $K -s 1G -t $T -o $OUT -C
	$JELLYFISH dump -c -t -L 2 $OUT > $OUT.temp&
	$SORT --parallel=$T -S 50% -T ./ $OUT.temp > $OUT.sorted.min2.tab &
	$JELLYFISH histo -f -o $OUT.histo $OUT & 
	wait
	rm $ParentGenerator.Jhash 
fi
