#!/bin/sh

echo "ok lets do this"

GEN=$1
K=$2
T=$3

RDIR="/opt/rufus/RUFUS"
JELLYFISH="$RDIR/src/externals/jellyfish-2.2.5/bin/jellyfish"
SORT="$RDIR/scripts/sort"
	
echo "$JELLYFISH"
$JELLYFISH


ulimit -v 30000000
ulimit -a
if [ -e "$GEN.Jhash.sorted.min2.tab" ]
then
        echo "Skipping jelly, $GEN.Jhash.Jhash.sorted.min2.tab alreads exists"
else
	echo "here"
	mkfifo $GEN.Jhash.temp
	/usr/bin/time -v $JELLYFISH count -G 20 -g $GEN -m $K -s 1G -t $T -o $GEN.Jhash -C
	/usr/bin/time -v $JELLYFISH dump -c -t -L 2 $GEN.Jhash > $GEN.Jhash.temp&
	/usr/bin/time -v $SORT --parallel=$T -S 50% -T ./ $GEN.Jhash.temp > $GEN.Jhash.sorted.min2.tab &
	/usr/bin/time -v $JELLYFISH histo -f -o $GEN.Jhash.histo $GEN.Jhash & 
	wait
	rm $GEN.Jhash
fi
